// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: count.sql

package sqlc

import (
	"context"
)

const countBackliteTasks = `-- name: CountBackliteTasks :one
SELECT COUNT(id) FROM example_table
`

// CountBackliteTasks
//
//	SELECT COUNT(id) FROM example_table
func (q *Queries) CountBackliteTasks(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countBackliteTasksStmt, countBackliteTasks)
	var count int64
	err := row.Scan(&count)
	return count, err
}
